#!/bin/bash
echo "Building a zip bundle with version timestamp for release"

# setup build dir
mkdir -p release
cp pshell.py release/__main__.py
cp parser.py release/parser.py
cp mfclient.py release/mfclient.py
cp s3client.py release/s3client.py
cd release

# stamp this release
d=$(date +%Y%m%d%H%M%S)
sed -i tmp -e 's/^build.*$/build="'$d'"/' __main__.py

# build
zip pshell.zip __main__.py parser.py mfclient.py s3client.py
echo "#!/usr/bin/env python3" > pshell
cat pshell.zip >> pshell
chmod u+x pshell

# cleanup
rm pshell.zip
rm __main__.py
rm parser.py
rm mfclient.py
rm s3client.py
rm *.pytmp

